url: https://inaaraali.github.io
baseurl: 

# Site settings
title: Inaara Ali
email: inaara.a.ali@gmail.com
description: "Hello world! My name is Inaara Ali, and I am an AI entrepreneur and early-career data scientist who conducted several analyses at Accenture for 2.5 years after graduating with a B.S. in Data Science (QSS) with an International Studies double major from Emory University. At Accenture, I was a Management Consulting Analyst in the Data & AI practice serving in various client-facing consulting engagements in the Health, Public Service, and Technology Industries. A life-long creative writer, I have a passion for storytelling and communicate meaningful insight from data to bring positive impact."


# Team names, titles and social links



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/inaaraali/
  - title: github
    url: https://gist.github.com/InaaraAli/starred 
  

    

# Postal address (add as many lines as necessary)
address:
  - line: 201 Dowman Dr
  - line: Atlanta, GA 30322 

# Build settings
markdown: kramdown
permalink: pretty
